package main

import (
	"net/http"
	"os"

	conf "github.com/LMS-Capstone-Project-Kelompok-49/Backend-Golang/internal/config"
	rest "github.com/LMS-Capstone-Project-Kelompok-49/Backend-Golang/internal/handler/restecho"
	"github.com/labstack/echo/v4"

	_ "github.com/LMS-Capstone-Project-Kelompok-49/Backend-Golang/docs" // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title Swagger Example API
// @version 1.0
// @description Sample API
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {

	config := conf.InitConfiguration()
	e := echo.New()

	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.GET("/", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]interface{}{
			"Message": "Welcome! You can check documentation at http://3.95.181.246/swagger/index.html !",
		})
	})

	e.GET("/.well-known/pki-validation/74A1B9BE28184B29ABE69EFFC2F14A2C.txt", func(c echo.Context) error {
		return c.String(http.StatusOK, "BC4E1CFF88134A28F3F6669E3BC13FB27C4AE54B605EC93650A241FCD2DBC261\ncomodoca.com\na90772fd87168ef")
	})
	os.Mkdir("temp", 0755)

	rest.RegisterUserGroupAPI(e, config)
	rest.RegisterCourseGroupAPI(e, config)
	rest.RegisterRoleGroupAPI(e, config)
	rest.RegisterMaterialGroupAPI(e, config)
	rest.RegisterCourseCategoryGroupAPI(e, config)
	rest.RegisterProfileGroupAPI(e, config)
	rest.RegisterCourseDetailAPI(e, config)
	rest.RegisterRatingAPI(e, config)
	rest.RegisterAssignmentAPI(e, config)

	e.Logger.Fatal(e.Start(":8000"))
}
