// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"github.com/swaggo/swag"
)


// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "54.236.5.123",
	BasePath:         "/app",
	Schemes:          []string{},
	Title:            "Docs",
	Description:      "Swagger docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

const docTemplate = `
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "capstone",
    "contact": {}
  },
  "host": "54.236.5.123",
  "basePath": "/",
  "securityDefinitions": {},
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "summary": "register",
        "tags": [
          "auth"
        ],
        "operationId": "register",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/registerrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "login",
        "tags": [
          "auth"
        ],
        "operationId": "login",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/loginrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/app/u": {
      "get": {
        "summary": "get_users",
        "tags": [
          "users"
        ],
        "operationId": "get_users",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/app/u/1": {
      "get": {
        "summary": "get_one_users",
        "tags": [
          "users"
        ],
        "operationId": "get_one_users",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "update_users",
        "tags": [
          "users"
        ],
        "operationId": "update_users",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/registerrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "delete_users",
        "tags": [
          "users"
        ],
        "operationId": "delete_users",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/app/c/create": {
      "post": {
        "summary": "create_course",
        "tags": [
          "course"
        ],
        "operationId": "create_course",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/create_course_request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/app/c/all": {
      "get": {
        "summary": "get_course",
        "tags": [
          "course"
        ],
        "operationId": "get_course",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/app/r": {
      "get": {
        "summary": "get_role",
        "tags": [
          "role"
        ],
        "operationId": "get_role",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/c/all": {
      "get": {
        "summary": "get_course Copy",
        "tags": [
          "lokal"
        ],
        "operationId": "get_courseCopy",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/c/create": {
      "post": {
        "summary": "create_course Copy",
        "tags": [
          "lokal"
        ],
        "operationId": "create_courseCopy",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-api-key",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/create_course_request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/role/1": {
      "get": {
        "summary": "get_role Copy",
        "tags": [
          "lokal"
        ],
        "operationId": "get_roleCopy",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/role/create": {
      "post": {
        "summary": "post_role Copy",
        "tags": [
          "lokal"
        ],
        "operationId": "post_roleCopy",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/post_roleCopyRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "definitions": {
    "registerrequest": {
      "title": "registerrequest",
      "example": {
        "name": "lawas",
        "email": "lawas@mail.com",
        "password": "lawss12345"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "password"
      ]
    },
    "loginrequest": {
      "title": "loginrequest",
      "example": {
        "email": "lawas@mail.com",
        "password": "lawss12345"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "create_course_request": {
      "title": "create_course_request",
      "example": {
        "mentorid": 1,
        "coursetype": 2,
        "category": 2,
        "coursename": "Halasena",
        "description": "Swabalah",
        "courseprice": "2 juta"
      },
      "type": "object",
      "properties": {
        "mentorid": {
          "type": "integer",
          "format": "int32"
        },
        "coursetype": {
          "type": "integer",
          "format": "int32"
        },
        "category": {
          "type": "integer",
          "format": "int32"
        },
        "coursename": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "courseprice": {
          "type": "string"
        }
      },
      "required": [
        "mentorid",
        "coursetype",
        "category",
        "coursename",
        "description",
        "courseprice"
      ]
    },
    "registerCopyRequest": {
      "title": "registerCopyRequest",
      "example": {
        "name": "Jauh",
        "email": "jauhin@mail.com",
        "password": "pajajauh"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "password"
      ]
    },
    "loginCopyRequest": {
      "title": "loginCopyRequest",
      "example": {
        "email": "jauhin@mail.com",
        "password": "pajajauh"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "post_roleCopyRequest": {
      "title": "post_roleCopyRequest",
      "example": {
        "rolename": "admin",
        "description": "Admin Bagian"
      },
      "type": "object",
      "properties": {
        "rolename": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "rolename",
        "description"
      ]
    }
  },
  "security": [],
  "tags": [
    {
      "name": "auth"
    },
    {
      "name": "users"
    },
    {
      "name": "course"
    },
    {
      "name": "role"
    },
    {
      "name": "lokal"
    }
  ]
}
`